base:
- base/fcn.yaml
quantization:
  should_finetune: true
  finetune_scheme:
    loss_factors:
    - 1.0
    dataset_size: 1000
    epochs: 4
    learning_rate: 0.0001
    loss_layer_names:
    - conv22
    loss_types:
    - l2
postprocessing:
  ext_upsample: 16
evaluation:
  labels_map:
  - 0
  - 1
  - 2
  - 2
  - 2
  - 3
  - 3
  - 3
  - 4
  - 4
  - 5
  - 6
  - 7
  - 7
  - 7
  - 7
  - 7
  - 7
  - 7
  classes: 8
network:
  network_name: fcn16_resnet_v1_18_8classes
allocation:
  required_fps: 36
paths:
  alls_script: fcn16_resnet_v1_18_8classes.alls
  network_path:
  - models_files/Segmentation/Cityscapes/fcn16_resnet_v1_18_8classes/pretrained/resnet18_fcn16.ckpt.meta
  - models_files/Segmentation/Cityscapes/fcn16_resnet_v1_18_8classes/pretrained/resnet18_fcn16.ckpt.index
  - models_files/Segmentation/Cityscapes/fcn16_resnet_v1_18_8classes/pretrained/resnet18_fcn16.ckpt.data-00000-of-00001
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/Segmentation/Cityscapes/fcn16_resnet_v1_18_8classes/pretrained/2021-07-11/fcn16_resnet_v1_18_8classes.zip
