base:
- base/fcn.yaml
quantization:
  should_finetune: true
  finetune_scheme:
    loss_factors:
    - 1.0
    dataset_size: 1000
    epochs: 4
    learning_rate: 0.0001
    loss_layer_names:
    - conv23
    loss_types:
    - l2
info:
  network_source: internal
network:
  network_name: fcn8_resnet_v1_18
allocation:
  required_fps: 30
paths:
  alls_script: fcn8_resnet_v1_18.alls
  network_path:
  - models_files/Segmentation/Cityscapes/fcn8_resnet_v1_18/pretrained/resnet18_fcn8.ckpt.meta
  - models_files/Segmentation/Cityscapes/fcn8_resnet_v1_18/pretrained/resnet18_fcn8.ckpt.index
  - models_files/Segmentation/Cityscapes/fcn8_resnet_v1_18/pretrained/resnet18_fcn8.ckpt.data-00000-of-00001
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/Segmentation/Cityscapes/fcn8_resnet_v1_18/pretrained/2021-07-11/fcn8_resnet_v1_18.zip
