base:
- base/yolo.yaml
preprocessing:
  input_shape: null
  meta_arch: mobilenet_ssd_ar
postprocessing:
  nms_iou_thresh: 0.3
  score_threshold: 0.1
  meta_arch: yolo_v3
  anchors:
    strides:
    - 16
    - 32
    sizes:
    - - 23
      - 27
      - 37
      - 58
      - 81
      - 82
    - - 81
      - 82
      - 135
      - 169
      - 344
      - 319
quantization:
  should_finetune: true
  finetune_scheme:
    loss_factors:
    - 1.0
    - 1.0
    dataset_size: 4000
    epochs: 8
    learning_rate: 0.0001
    loss_types:
    - l2
    - l2
allocation:
  required_fps: 1009
network:
  network_name: tiny_yolov3
paths:
  alls_script: tiny_yolov3.alls
  network_path:
  - models_files/ObjectDetection/Detection-COCO/yolo/tiny_yolov3/pretrained/frozen_tiny_yolo_v3.pb
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ObjectDetection/Detection-COCO/yolo/tiny_yolov3/pretrained/2021-07-11/tiny_yolov3.zip
parser:
  nodes:
  - import/detector/yolo-v3-tiny/Conv/Conv2D
  - - import/detector/yolo-v3-tiny/Conv_9/BiasAdd
    - import/detector/yolo-v3-tiny/Conv_12/BiasAdd
