base:
- base/yolo.yaml
postprocessing:
  anchors:
    sizes:
    - - 10
      - 13
      - 16
      - 30
      - 33
      - 23
    - - 30
      - 61
      - 62
      - 45
      - 59
      - 119
    - - 116
      - 90
      - 156
      - 198
      - 373
      - 326
  meta_arch: yolo_v3
hn_editor:
  output_scheme:
    outputs_to_split:
    - conv83
    - conv91
    - conv98
    split_output: true
info:
  network_source: https://github.com/AlexeyAB/darknet
quantization:
  quantization_batch_size: 2
  should_finetune: true
  finetune_scheme:
    loss_factors:
    - 1.0
    - 2.0
    - 0.25
    - 0.125
    - 1.0
    - 2.0
    - 0.25
    - 0.125
    - 1.0
    - 2.0
    - 0.25
    - 0.125
    dataset_size: 4000
    epochs: 8
    learning_rate: 0.0001
    loss_types:
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
allocation:
  required_fps: 100
preprocessing:
  input_shape:
  - 608
  - 608
  - 3
  meta_arch: yolo_v3
network:
  network_name: yolov3
paths:
  alls_script: yolov3.alls
  network_path:
  - models_files/ObjectDetection/Detection-COCO/yolo/yolov3/pretrained/2021-08-16/yolov3_1_3_608_608_static.onnx
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ObjectDetection/Detection-COCO/yolo/yolov3/pretrained/2021-08-16/yolov3.zip
parser:
  ew_add_policy: fused_conv_and_add_identity_fallback
  nodes:
  - input
  - - Conv_865
    - Conv_502
    - Conv_139
