base:
- base/yolo.yaml
postprocessing:
  anchors:
    sizes:
    - - 10
      - 13
      - 16
      - 30
      - 33
      - 23
    - - 30
      - 61
      - 62
      - 45
      - 59
      - 119
    - - 116
      - 90
      - 156
      - 198
      - 373
      - 326
  meta_arch: yolo_v3
hn_editor:
  output_scheme:
    outputs_to_split:
    - conv60
    - conv68
    - conv75
    split_output: true
info:
  network_source: https://github.com/AlexeyAB/darknet
quantization:
  should_finetune: true
  finetune_scheme:
    loss_factors:
    - 1.0
    - 2.0
    - 0.25
    - 0.125
    - 1.0
    - 2.0
    - 0.25
    - 0.125
    - 1.0
    - 2.0
    - 0.25
    - 0.125
    dataset_size: 4000
    epochs: 8
    learning_rate: 0.0001
    loss_types:
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
    - l2
allocation:
  required_fps: 200
preprocessing:
  input_shape:
  - 416
  - 416
  - 3
  meta_arch: yolo_v3
network:
  network_name: yolov3_416
paths:
  alls_script: yolov3_416.alls
  network_path:
  - models_files/ObjectDetection/Detection-COCO/yolo/yolov3_416/pretrained/2021-08-16/yolov3_1_3_416_416_static.onnx
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ObjectDetection/Detection-COCO/yolo/yolov3_416/pretrained/2021-08-16/yolov3_416.zip
parser:
  nodes:
  - input
  - - Conv_865
    - Conv_502
    - Conv_139
