base:
- base/yolo.yaml
quantization:
  should_finetune: true
  finetune_scheme:
    learning_rate: 0.0002
    epochs: 8
    dataset_size: 2048
preprocessing:
  input_shape:
  - 512
  - 512
  - 3
hn_editor:
  output_scheme:
    change_activations:
      enabled: true
      changes:
      - layer_name: conv69
        activation: sigmoid
      - layer_name: conv61
        activation: sigmoid
      - layer_name: conv53
        activation: sigmoid
network:
  network_name: yolov5xs
allocation:
  required_fps: 900
paths:
  network_path:
  - models_files/ObjectDetection/Detection-COCO/yolo/yolov5xs/pretrained/yolov5s512.onnx
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ObjectDetection/Detection-COCO/yolo/yolov5xs/pretrained/2021-07-11/yolov5xs.zip
parser:
  nodes:
  - null
  - - Conv_252
    - Conv_235
    - Conv_218
  start_node_shape:
  - 1
  - 3
  - 512
  - 512
